### ISSUE TITLE
Command Issue

### ISSUE THREAD

**Issue by SuperDude36** [KairusDarkSeeker/PrivateVaults#2]
When I do /pv 1 it says opening vault as a popup or tip, but it doesn't open the vault.

**Comment by KairusDarkSeeker** [comment]
I'll fix it soon

**Comment by SuperDude36** [comment]
Ok, thanks! I have been looking for this plugin a long time :)

**Comment by SuperDude36** [comment]
make the chest appear inside the player and have a invis bedrock on top so other players can't access it.

**Comment by KairusDarkSeeker** [comment]
can you elaborate?

**Comment by SuperDude36** [comment]
I think the problem is that a player can't open a chest from more than 10 blocks away so, if you make the chest appear inside the player, the vault would open. The problem with that is that other players could open it. Maybe also while the players on the vault, it will spawn in the chest with a border block on top.

**Comment by KairusDarkSeeker** [comment]
explain

**Comment by SuperDude36** [comment]
nvm

**Comment by KairusDarkSeeker** [comment]
@SuperDude36 I'll improve the plugin soon :)

**Comment by SuperDude36** [comment]
Ok :)
