### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by SuperDude36** [KairusDarkSeeker/PrivateVaults#3]
Now all it does is put a chest 4 blocks beneath you. The chests don't link anyways.

**Comment by KairusDarkSeeker** [comment]
hmm its a problem with genisys, I can't tell whether its a bug

**Comment by SuperDude36** [comment]
Oh

**Comment by SuperDude36** [comment]
How did @Musqit do it on CosmicPE?

**Comment by KairusDarkSeeker** [comment]
its made by CraftBukkit

**Comment by SuperDude36** [comment]
Oh

**Comment by SuperDude36** [comment]
I wish musqit made the /sell all part of his Sell plugin public

**Comment by SuperDude36** [comment]
I just finished modifying factions pro :3

**Comment by SuperDude36** [comment]
Ima post phar
